### ISSUE TITLE
There is Missing of Keys File @Wavy-Fish/core/src/com/stefanosiano/wavyfish/__________

### ISSUE THREAD

**Issue by arunkiddo** [stefanosiano/Wavy-Fish#1]
There is a file Missing(Key).Please Check it out.

The Location Where the file Should be is @ Wavy-Fish/core/src/com/stefanosiano/wavyfish/_____Keys___________

**Comment by stefanosiano** [comment]
That's true,
but that's a class containing the keys of my own accounts for advertisements and analytics, so I can't include them.
Just create empty strings, if you don't have advertisements accounts
